CFLAGS=-Wall -g

all: ex1 ex3 ex4 ex7 ex8 ex10 ex11 ex12 ex13 ex14 ex16 ex17 ex18 ex19 ex_22 ex23 ex24 ex25

ex_22:
	cc $(CFLAGS) -c -o ex22.o ex22.c
	cc $(CFLAGS)  ex22_main.c ex22.o -o ex22_main

clean:
	rm -fr ex1 ex3 ex4 ex7 ex8 ex10 ex11 ex12 ex13 ex14 ex16 ex17 ex18 ex19 ex22_main ex23 ex24 ex25
